---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage0
  namespace: tools
spec:
  project: default
  source:
    repoURL: https://github.com/mikolajgasior/argocd-apps-preview
    targetRevision: HEAD
    path: example/stage0-app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {}
