apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage1-app
  namespace: tools
spec:
  project: stage1
  source:
    repoURL: https://github.com/keenbytes/argocd-apps-preview
    targetRevision: main
    path: example/stage1-app
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated: {}
