apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stage3
  namespace: tools
spec:
  description: Description
  sourceRepos:
    - https://github.com/keenbytes/argocd-apps-preview
  destinations:
    - server: https://kubernetes.default.svc
      namespace: tools
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
